# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lucas/delivery/CPP/cpp_indie_studio

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lucas/delivery/CPP/cpp_indie_studio

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lucas/delivery/CPP/cpp_indie_studio/CMakeFiles /home/lucas/delivery/CPP/cpp_indie_studio/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lucas/delivery/CPP/cpp_indie_studio/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bomberman

# Build rule for target.
bomberman: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bomberman
.PHONY : bomberman

# fast build rule for target.
bomberman/fast:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/build
.PHONY : bomberman/fast

Src/Entity/AEntity.o: Src/Entity/AEntity.cpp.o

.PHONY : Src/Entity/AEntity.o

# target to build an object file
Src/Entity/AEntity.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/Entity/AEntity.cpp.o
.PHONY : Src/Entity/AEntity.cpp.o

Src/Entity/AEntity.i: Src/Entity/AEntity.cpp.i

.PHONY : Src/Entity/AEntity.i

# target to preprocess a source file
Src/Entity/AEntity.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/Entity/AEntity.cpp.i
.PHONY : Src/Entity/AEntity.cpp.i

Src/Entity/AEntity.s: Src/Entity/AEntity.cpp.s

.PHONY : Src/Entity/AEntity.s

# target to generate assembly for a file
Src/Entity/AEntity.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/Entity/AEntity.cpp.s
.PHONY : Src/Entity/AEntity.cpp.s

Src/Entity/Bomb/Bomb.o: Src/Entity/Bomb/Bomb.cpp.o

.PHONY : Src/Entity/Bomb/Bomb.o

# target to build an object file
Src/Entity/Bomb/Bomb.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/Entity/Bomb/Bomb.cpp.o
.PHONY : Src/Entity/Bomb/Bomb.cpp.o

Src/Entity/Bomb/Bomb.i: Src/Entity/Bomb/Bomb.cpp.i

.PHONY : Src/Entity/Bomb/Bomb.i

# target to preprocess a source file
Src/Entity/Bomb/Bomb.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/Entity/Bomb/Bomb.cpp.i
.PHONY : Src/Entity/Bomb/Bomb.cpp.i

Src/Entity/Bomb/Bomb.s: Src/Entity/Bomb/Bomb.cpp.s

.PHONY : Src/Entity/Bomb/Bomb.s

# target to generate assembly for a file
Src/Entity/Bomb/Bomb.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/Entity/Bomb/Bomb.cpp.s
.PHONY : Src/Entity/Bomb/Bomb.cpp.s

Src/Entity/Bomb/Timer.o: Src/Entity/Bomb/Timer.cpp.o

.PHONY : Src/Entity/Bomb/Timer.o

# target to build an object file
Src/Entity/Bomb/Timer.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/Entity/Bomb/Timer.cpp.o
.PHONY : Src/Entity/Bomb/Timer.cpp.o

Src/Entity/Bomb/Timer.i: Src/Entity/Bomb/Timer.cpp.i

.PHONY : Src/Entity/Bomb/Timer.i

# target to preprocess a source file
Src/Entity/Bomb/Timer.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/Entity/Bomb/Timer.cpp.i
.PHONY : Src/Entity/Bomb/Timer.cpp.i

Src/Entity/Bomb/Timer.s: Src/Entity/Bomb/Timer.cpp.s

.PHONY : Src/Entity/Bomb/Timer.s

# target to generate assembly for a file
Src/Entity/Bomb/Timer.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/Entity/Bomb/Timer.cpp.s
.PHONY : Src/Entity/Bomb/Timer.cpp.s

Src/Entity/Character/ACharacter.o: Src/Entity/Character/ACharacter.cpp.o

.PHONY : Src/Entity/Character/ACharacter.o

# target to build an object file
Src/Entity/Character/ACharacter.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/Entity/Character/ACharacter.cpp.o
.PHONY : Src/Entity/Character/ACharacter.cpp.o

Src/Entity/Character/ACharacter.i: Src/Entity/Character/ACharacter.cpp.i

.PHONY : Src/Entity/Character/ACharacter.i

# target to preprocess a source file
Src/Entity/Character/ACharacter.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/Entity/Character/ACharacter.cpp.i
.PHONY : Src/Entity/Character/ACharacter.cpp.i

Src/Entity/Character/ACharacter.s: Src/Entity/Character/ACharacter.cpp.s

.PHONY : Src/Entity/Character/ACharacter.s

# target to generate assembly for a file
Src/Entity/Character/ACharacter.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/Entity/Character/ACharacter.cpp.s
.PHONY : Src/Entity/Character/ACharacter.cpp.s

Src/Entity/Character/AI/AAI.o: Src/Entity/Character/AI/AAI.cpp.o

.PHONY : Src/Entity/Character/AI/AAI.o

# target to build an object file
Src/Entity/Character/AI/AAI.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/Entity/Character/AI/AAI.cpp.o
.PHONY : Src/Entity/Character/AI/AAI.cpp.o

Src/Entity/Character/AI/AAI.i: Src/Entity/Character/AI/AAI.cpp.i

.PHONY : Src/Entity/Character/AI/AAI.i

# target to preprocess a source file
Src/Entity/Character/AI/AAI.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/Entity/Character/AI/AAI.cpp.i
.PHONY : Src/Entity/Character/AI/AAI.cpp.i

Src/Entity/Character/AI/AAI.s: Src/Entity/Character/AI/AAI.cpp.s

.PHONY : Src/Entity/Character/AI/AAI.s

# target to generate assembly for a file
Src/Entity/Character/AI/AAI.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/Entity/Character/AI/AAI.cpp.s
.PHONY : Src/Entity/Character/AI/AAI.cpp.s

Src/Entity/Character/AI/ArtificialIntelligence.o: Src/Entity/Character/AI/ArtificialIntelligence.cpp.o

.PHONY : Src/Entity/Character/AI/ArtificialIntelligence.o

# target to build an object file
Src/Entity/Character/AI/ArtificialIntelligence.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/Entity/Character/AI/ArtificialIntelligence.cpp.o
.PHONY : Src/Entity/Character/AI/ArtificialIntelligence.cpp.o

Src/Entity/Character/AI/ArtificialIntelligence.i: Src/Entity/Character/AI/ArtificialIntelligence.cpp.i

.PHONY : Src/Entity/Character/AI/ArtificialIntelligence.i

# target to preprocess a source file
Src/Entity/Character/AI/ArtificialIntelligence.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/Entity/Character/AI/ArtificialIntelligence.cpp.i
.PHONY : Src/Entity/Character/AI/ArtificialIntelligence.cpp.i

Src/Entity/Character/AI/ArtificialIntelligence.s: Src/Entity/Character/AI/ArtificialIntelligence.cpp.s

.PHONY : Src/Entity/Character/AI/ArtificialIntelligence.s

# target to generate assembly for a file
Src/Entity/Character/AI/ArtificialIntelligence.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/Entity/Character/AI/ArtificialIntelligence.cpp.s
.PHONY : Src/Entity/Character/AI/ArtificialIntelligence.cpp.s

Src/Entity/PowerUp/APowerUp.o: Src/Entity/PowerUp/APowerUp.cpp.o

.PHONY : Src/Entity/PowerUp/APowerUp.o

# target to build an object file
Src/Entity/PowerUp/APowerUp.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/Entity/PowerUp/APowerUp.cpp.o
.PHONY : Src/Entity/PowerUp/APowerUp.cpp.o

Src/Entity/PowerUp/APowerUp.i: Src/Entity/PowerUp/APowerUp.cpp.i

.PHONY : Src/Entity/PowerUp/APowerUp.i

# target to preprocess a source file
Src/Entity/PowerUp/APowerUp.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/Entity/PowerUp/APowerUp.cpp.i
.PHONY : Src/Entity/PowerUp/APowerUp.cpp.i

Src/Entity/PowerUp/APowerUp.s: Src/Entity/PowerUp/APowerUp.cpp.s

.PHONY : Src/Entity/PowerUp/APowerUp.s

# target to generate assembly for a file
Src/Entity/PowerUp/APowerUp.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/Entity/PowerUp/APowerUp.cpp.s
.PHONY : Src/Entity/PowerUp/APowerUp.cpp.s

Src/Entity/PowerUp/BombUp/BombUp.o: Src/Entity/PowerUp/BombUp/BombUp.cpp.o

.PHONY : Src/Entity/PowerUp/BombUp/BombUp.o

# target to build an object file
Src/Entity/PowerUp/BombUp/BombUp.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/Entity/PowerUp/BombUp/BombUp.cpp.o
.PHONY : Src/Entity/PowerUp/BombUp/BombUp.cpp.o

Src/Entity/PowerUp/BombUp/BombUp.i: Src/Entity/PowerUp/BombUp/BombUp.cpp.i

.PHONY : Src/Entity/PowerUp/BombUp/BombUp.i

# target to preprocess a source file
Src/Entity/PowerUp/BombUp/BombUp.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/Entity/PowerUp/BombUp/BombUp.cpp.i
.PHONY : Src/Entity/PowerUp/BombUp/BombUp.cpp.i

Src/Entity/PowerUp/BombUp/BombUp.s: Src/Entity/PowerUp/BombUp/BombUp.cpp.s

.PHONY : Src/Entity/PowerUp/BombUp/BombUp.s

# target to generate assembly for a file
Src/Entity/PowerUp/BombUp/BombUp.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/Entity/PowerUp/BombUp/BombUp.cpp.s
.PHONY : Src/Entity/PowerUp/BombUp/BombUp.cpp.s

Src/Entity/PowerUp/FireUp/FireUp.o: Src/Entity/PowerUp/FireUp/FireUp.cpp.o

.PHONY : Src/Entity/PowerUp/FireUp/FireUp.o

# target to build an object file
Src/Entity/PowerUp/FireUp/FireUp.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/Entity/PowerUp/FireUp/FireUp.cpp.o
.PHONY : Src/Entity/PowerUp/FireUp/FireUp.cpp.o

Src/Entity/PowerUp/FireUp/FireUp.i: Src/Entity/PowerUp/FireUp/FireUp.cpp.i

.PHONY : Src/Entity/PowerUp/FireUp/FireUp.i

# target to preprocess a source file
Src/Entity/PowerUp/FireUp/FireUp.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/Entity/PowerUp/FireUp/FireUp.cpp.i
.PHONY : Src/Entity/PowerUp/FireUp/FireUp.cpp.i

Src/Entity/PowerUp/FireUp/FireUp.s: Src/Entity/PowerUp/FireUp/FireUp.cpp.s

.PHONY : Src/Entity/PowerUp/FireUp/FireUp.s

# target to generate assembly for a file
Src/Entity/PowerUp/FireUp/FireUp.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/Entity/PowerUp/FireUp/FireUp.cpp.s
.PHONY : Src/Entity/PowerUp/FireUp/FireUp.cpp.s

Src/Entity/PowerUp/SpeedUp/SpeedUp.o: Src/Entity/PowerUp/SpeedUp/SpeedUp.cpp.o

.PHONY : Src/Entity/PowerUp/SpeedUp/SpeedUp.o

# target to build an object file
Src/Entity/PowerUp/SpeedUp/SpeedUp.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/Entity/PowerUp/SpeedUp/SpeedUp.cpp.o
.PHONY : Src/Entity/PowerUp/SpeedUp/SpeedUp.cpp.o

Src/Entity/PowerUp/SpeedUp/SpeedUp.i: Src/Entity/PowerUp/SpeedUp/SpeedUp.cpp.i

.PHONY : Src/Entity/PowerUp/SpeedUp/SpeedUp.i

# target to preprocess a source file
Src/Entity/PowerUp/SpeedUp/SpeedUp.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/Entity/PowerUp/SpeedUp/SpeedUp.cpp.i
.PHONY : Src/Entity/PowerUp/SpeedUp/SpeedUp.cpp.i

Src/Entity/PowerUp/SpeedUp/SpeedUp.s: Src/Entity/PowerUp/SpeedUp/SpeedUp.cpp.s

.PHONY : Src/Entity/PowerUp/SpeedUp/SpeedUp.s

# target to generate assembly for a file
Src/Entity/PowerUp/SpeedUp/SpeedUp.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/Entity/PowerUp/SpeedUp/SpeedUp.cpp.s
.PHONY : Src/Entity/PowerUp/SpeedUp/SpeedUp.cpp.s

Src/Entity/PowerUp/WallPass/WallPass.o: Src/Entity/PowerUp/WallPass/WallPass.cpp.o

.PHONY : Src/Entity/PowerUp/WallPass/WallPass.o

# target to build an object file
Src/Entity/PowerUp/WallPass/WallPass.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/Entity/PowerUp/WallPass/WallPass.cpp.o
.PHONY : Src/Entity/PowerUp/WallPass/WallPass.cpp.o

Src/Entity/PowerUp/WallPass/WallPass.i: Src/Entity/PowerUp/WallPass/WallPass.cpp.i

.PHONY : Src/Entity/PowerUp/WallPass/WallPass.i

# target to preprocess a source file
Src/Entity/PowerUp/WallPass/WallPass.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/Entity/PowerUp/WallPass/WallPass.cpp.i
.PHONY : Src/Entity/PowerUp/WallPass/WallPass.cpp.i

Src/Entity/PowerUp/WallPass/WallPass.s: Src/Entity/PowerUp/WallPass/WallPass.cpp.s

.PHONY : Src/Entity/PowerUp/WallPass/WallPass.s

# target to generate assembly for a file
Src/Entity/PowerUp/WallPass/WallPass.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/Entity/PowerUp/WallPass/WallPass.cpp.s
.PHONY : Src/Entity/PowerUp/WallPass/WallPass.cpp.s

Src/Entity/Scenery/Explosion/Explosion.o: Src/Entity/Scenery/Explosion/Explosion.cpp.o

.PHONY : Src/Entity/Scenery/Explosion/Explosion.o

# target to build an object file
Src/Entity/Scenery/Explosion/Explosion.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/Entity/Scenery/Explosion/Explosion.cpp.o
.PHONY : Src/Entity/Scenery/Explosion/Explosion.cpp.o

Src/Entity/Scenery/Explosion/Explosion.i: Src/Entity/Scenery/Explosion/Explosion.cpp.i

.PHONY : Src/Entity/Scenery/Explosion/Explosion.i

# target to preprocess a source file
Src/Entity/Scenery/Explosion/Explosion.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/Entity/Scenery/Explosion/Explosion.cpp.i
.PHONY : Src/Entity/Scenery/Explosion/Explosion.cpp.i

Src/Entity/Scenery/Explosion/Explosion.s: Src/Entity/Scenery/Explosion/Explosion.cpp.s

.PHONY : Src/Entity/Scenery/Explosion/Explosion.s

# target to generate assembly for a file
Src/Entity/Scenery/Explosion/Explosion.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/Entity/Scenery/Explosion/Explosion.cpp.s
.PHONY : Src/Entity/Scenery/Explosion/Explosion.cpp.s

Src/Entity/Scenery/UnbreakableWall/UnbreakableWall.o: Src/Entity/Scenery/UnbreakableWall/UnbreakableWall.cpp.o

.PHONY : Src/Entity/Scenery/UnbreakableWall/UnbreakableWall.o

# target to build an object file
Src/Entity/Scenery/UnbreakableWall/UnbreakableWall.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/Entity/Scenery/UnbreakableWall/UnbreakableWall.cpp.o
.PHONY : Src/Entity/Scenery/UnbreakableWall/UnbreakableWall.cpp.o

Src/Entity/Scenery/UnbreakableWall/UnbreakableWall.i: Src/Entity/Scenery/UnbreakableWall/UnbreakableWall.cpp.i

.PHONY : Src/Entity/Scenery/UnbreakableWall/UnbreakableWall.i

# target to preprocess a source file
Src/Entity/Scenery/UnbreakableWall/UnbreakableWall.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/Entity/Scenery/UnbreakableWall/UnbreakableWall.cpp.i
.PHONY : Src/Entity/Scenery/UnbreakableWall/UnbreakableWall.cpp.i

Src/Entity/Scenery/UnbreakableWall/UnbreakableWall.s: Src/Entity/Scenery/UnbreakableWall/UnbreakableWall.cpp.s

.PHONY : Src/Entity/Scenery/UnbreakableWall/UnbreakableWall.s

# target to generate assembly for a file
Src/Entity/Scenery/UnbreakableWall/UnbreakableWall.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/Entity/Scenery/UnbreakableWall/UnbreakableWall.cpp.s
.PHONY : Src/Entity/Scenery/UnbreakableWall/UnbreakableWall.cpp.s

Src/Entity/Scenery/Wall/Wall.o: Src/Entity/Scenery/Wall/Wall.cpp.o

.PHONY : Src/Entity/Scenery/Wall/Wall.o

# target to build an object file
Src/Entity/Scenery/Wall/Wall.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/Entity/Scenery/Wall/Wall.cpp.o
.PHONY : Src/Entity/Scenery/Wall/Wall.cpp.o

Src/Entity/Scenery/Wall/Wall.i: Src/Entity/Scenery/Wall/Wall.cpp.i

.PHONY : Src/Entity/Scenery/Wall/Wall.i

# target to preprocess a source file
Src/Entity/Scenery/Wall/Wall.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/Entity/Scenery/Wall/Wall.cpp.i
.PHONY : Src/Entity/Scenery/Wall/Wall.cpp.i

Src/Entity/Scenery/Wall/Wall.s: Src/Entity/Scenery/Wall/Wall.cpp.s

.PHONY : Src/Entity/Scenery/Wall/Wall.s

# target to generate assembly for a file
Src/Entity/Scenery/Wall/Wall.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/Entity/Scenery/Wall/Wall.cpp.s
.PHONY : Src/Entity/Scenery/Wall/Wall.cpp.s

Src/GameEngine/EventManager.o: Src/GameEngine/EventManager.cpp.o

.PHONY : Src/GameEngine/EventManager.o

# target to build an object file
Src/GameEngine/EventManager.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/GameEngine/EventManager.cpp.o
.PHONY : Src/GameEngine/EventManager.cpp.o

Src/GameEngine/EventManager.i: Src/GameEngine/EventManager.cpp.i

.PHONY : Src/GameEngine/EventManager.i

# target to preprocess a source file
Src/GameEngine/EventManager.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/GameEngine/EventManager.cpp.i
.PHONY : Src/GameEngine/EventManager.cpp.i

Src/GameEngine/EventManager.s: Src/GameEngine/EventManager.cpp.s

.PHONY : Src/GameEngine/EventManager.s

# target to generate assembly for a file
Src/GameEngine/EventManager.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/GameEngine/EventManager.cpp.s
.PHONY : Src/GameEngine/EventManager.cpp.s

Src/GameEngine/ManageIrrlicht.o: Src/GameEngine/ManageIrrlicht.cpp.o

.PHONY : Src/GameEngine/ManageIrrlicht.o

# target to build an object file
Src/GameEngine/ManageIrrlicht.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/GameEngine/ManageIrrlicht.cpp.o
.PHONY : Src/GameEngine/ManageIrrlicht.cpp.o

Src/GameEngine/ManageIrrlicht.i: Src/GameEngine/ManageIrrlicht.cpp.i

.PHONY : Src/GameEngine/ManageIrrlicht.i

# target to preprocess a source file
Src/GameEngine/ManageIrrlicht.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/GameEngine/ManageIrrlicht.cpp.i
.PHONY : Src/GameEngine/ManageIrrlicht.cpp.i

Src/GameEngine/ManageIrrlicht.s: Src/GameEngine/ManageIrrlicht.cpp.s

.PHONY : Src/GameEngine/ManageIrrlicht.s

# target to generate assembly for a file
Src/GameEngine/ManageIrrlicht.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/GameEngine/ManageIrrlicht.cpp.s
.PHONY : Src/GameEngine/ManageIrrlicht.cpp.s

Src/GameEngine/ManageObject.o: Src/GameEngine/ManageObject.cpp.o

.PHONY : Src/GameEngine/ManageObject.o

# target to build an object file
Src/GameEngine/ManageObject.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/GameEngine/ManageObject.cpp.o
.PHONY : Src/GameEngine/ManageObject.cpp.o

Src/GameEngine/ManageObject.i: Src/GameEngine/ManageObject.cpp.i

.PHONY : Src/GameEngine/ManageObject.i

# target to preprocess a source file
Src/GameEngine/ManageObject.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/GameEngine/ManageObject.cpp.i
.PHONY : Src/GameEngine/ManageObject.cpp.i

Src/GameEngine/ManageObject.s: Src/GameEngine/ManageObject.cpp.s

.PHONY : Src/GameEngine/ManageObject.s

# target to generate assembly for a file
Src/GameEngine/ManageObject.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/GameEngine/ManageObject.cpp.s
.PHONY : Src/GameEngine/ManageObject.cpp.s

Src/Main.o: Src/Main.cpp.o

.PHONY : Src/Main.o

# target to build an object file
Src/Main.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/Main.cpp.o
.PHONY : Src/Main.cpp.o

Src/Main.i: Src/Main.cpp.i

.PHONY : Src/Main.i

# target to preprocess a source file
Src/Main.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/Main.cpp.i
.PHONY : Src/Main.cpp.i

Src/Main.s: Src/Main.cpp.s

.PHONY : Src/Main.s

# target to generate assembly for a file
Src/Main.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/Main.cpp.s
.PHONY : Src/Main.cpp.s

Src/MapGenerator/MapGenerator.o: Src/MapGenerator/MapGenerator.cpp.o

.PHONY : Src/MapGenerator/MapGenerator.o

# target to build an object file
Src/MapGenerator/MapGenerator.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/MapGenerator/MapGenerator.cpp.o
.PHONY : Src/MapGenerator/MapGenerator.cpp.o

Src/MapGenerator/MapGenerator.i: Src/MapGenerator/MapGenerator.cpp.i

.PHONY : Src/MapGenerator/MapGenerator.i

# target to preprocess a source file
Src/MapGenerator/MapGenerator.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/MapGenerator/MapGenerator.cpp.i
.PHONY : Src/MapGenerator/MapGenerator.cpp.i

Src/MapGenerator/MapGenerator.s: Src/MapGenerator/MapGenerator.cpp.s

.PHONY : Src/MapGenerator/MapGenerator.s

# target to generate assembly for a file
Src/MapGenerator/MapGenerator.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/MapGenerator/MapGenerator.cpp.s
.PHONY : Src/MapGenerator/MapGenerator.cpp.s

Src/Tools/Thread.o: Src/Tools/Thread.cpp.o

.PHONY : Src/Tools/Thread.o

# target to build an object file
Src/Tools/Thread.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/Tools/Thread.cpp.o
.PHONY : Src/Tools/Thread.cpp.o

Src/Tools/Thread.i: Src/Tools/Thread.cpp.i

.PHONY : Src/Tools/Thread.i

# target to preprocess a source file
Src/Tools/Thread.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/Tools/Thread.cpp.i
.PHONY : Src/Tools/Thread.cpp.i

Src/Tools/Thread.s: Src/Tools/Thread.cpp.s

.PHONY : Src/Tools/Thread.s

# target to generate assembly for a file
Src/Tools/Thread.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/Tools/Thread.cpp.s
.PHONY : Src/Tools/Thread.cpp.s

Src/Tools/ThreadPool.o: Src/Tools/ThreadPool.cpp.o

.PHONY : Src/Tools/ThreadPool.o

# target to build an object file
Src/Tools/ThreadPool.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/Tools/ThreadPool.cpp.o
.PHONY : Src/Tools/ThreadPool.cpp.o

Src/Tools/ThreadPool.i: Src/Tools/ThreadPool.cpp.i

.PHONY : Src/Tools/ThreadPool.i

# target to preprocess a source file
Src/Tools/ThreadPool.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/Tools/ThreadPool.cpp.i
.PHONY : Src/Tools/ThreadPool.cpp.i

Src/Tools/ThreadPool.s: Src/Tools/ThreadPool.cpp.s

.PHONY : Src/Tools/ThreadPool.s

# target to generate assembly for a file
Src/Tools/ThreadPool.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Src/Tools/ThreadPool.cpp.s
.PHONY : Src/Tools/ThreadPool.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... bomberman"
	@echo "... edit_cache"
	@echo "... Src/Entity/AEntity.o"
	@echo "... Src/Entity/AEntity.i"
	@echo "... Src/Entity/AEntity.s"
	@echo "... Src/Entity/Bomb/Bomb.o"
	@echo "... Src/Entity/Bomb/Bomb.i"
	@echo "... Src/Entity/Bomb/Bomb.s"
	@echo "... Src/Entity/Bomb/Timer.o"
	@echo "... Src/Entity/Bomb/Timer.i"
	@echo "... Src/Entity/Bomb/Timer.s"
	@echo "... Src/Entity/Character/ACharacter.o"
	@echo "... Src/Entity/Character/ACharacter.i"
	@echo "... Src/Entity/Character/ACharacter.s"
	@echo "... Src/Entity/Character/AI/AAI.o"
	@echo "... Src/Entity/Character/AI/AAI.i"
	@echo "... Src/Entity/Character/AI/AAI.s"
	@echo "... Src/Entity/Character/AI/ArtificialIntelligence.o"
	@echo "... Src/Entity/Character/AI/ArtificialIntelligence.i"
	@echo "... Src/Entity/Character/AI/ArtificialIntelligence.s"
	@echo "... Src/Entity/PowerUp/APowerUp.o"
	@echo "... Src/Entity/PowerUp/APowerUp.i"
	@echo "... Src/Entity/PowerUp/APowerUp.s"
	@echo "... Src/Entity/PowerUp/BombUp/BombUp.o"
	@echo "... Src/Entity/PowerUp/BombUp/BombUp.i"
	@echo "... Src/Entity/PowerUp/BombUp/BombUp.s"
	@echo "... Src/Entity/PowerUp/FireUp/FireUp.o"
	@echo "... Src/Entity/PowerUp/FireUp/FireUp.i"
	@echo "... Src/Entity/PowerUp/FireUp/FireUp.s"
	@echo "... Src/Entity/PowerUp/SpeedUp/SpeedUp.o"
	@echo "... Src/Entity/PowerUp/SpeedUp/SpeedUp.i"
	@echo "... Src/Entity/PowerUp/SpeedUp/SpeedUp.s"
	@echo "... Src/Entity/PowerUp/WallPass/WallPass.o"
	@echo "... Src/Entity/PowerUp/WallPass/WallPass.i"
	@echo "... Src/Entity/PowerUp/WallPass/WallPass.s"
	@echo "... Src/Entity/Scenery/Explosion/Explosion.o"
	@echo "... Src/Entity/Scenery/Explosion/Explosion.i"
	@echo "... Src/Entity/Scenery/Explosion/Explosion.s"
	@echo "... Src/Entity/Scenery/UnbreakableWall/UnbreakableWall.o"
	@echo "... Src/Entity/Scenery/UnbreakableWall/UnbreakableWall.i"
	@echo "... Src/Entity/Scenery/UnbreakableWall/UnbreakableWall.s"
	@echo "... Src/Entity/Scenery/Wall/Wall.o"
	@echo "... Src/Entity/Scenery/Wall/Wall.i"
	@echo "... Src/Entity/Scenery/Wall/Wall.s"
	@echo "... Src/GameEngine/EventManager.o"
	@echo "... Src/GameEngine/EventManager.i"
	@echo "... Src/GameEngine/EventManager.s"
	@echo "... Src/GameEngine/ManageIrrlicht.o"
	@echo "... Src/GameEngine/ManageIrrlicht.i"
	@echo "... Src/GameEngine/ManageIrrlicht.s"
	@echo "... Src/GameEngine/ManageObject.o"
	@echo "... Src/GameEngine/ManageObject.i"
	@echo "... Src/GameEngine/ManageObject.s"
	@echo "... Src/Main.o"
	@echo "... Src/Main.i"
	@echo "... Src/Main.s"
	@echo "... Src/MapGenerator/MapGenerator.o"
	@echo "... Src/MapGenerator/MapGenerator.i"
	@echo "... Src/MapGenerator/MapGenerator.s"
	@echo "... Src/Tools/Thread.o"
	@echo "... Src/Tools/Thread.i"
	@echo "... Src/Tools/Thread.s"
	@echo "... Src/Tools/ThreadPool.o"
	@echo "... Src/Tools/ThreadPool.i"
	@echo "... Src/Tools/ThreadPool.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

